export enum AreasConhecimento {
  MATEMATICA = "Matemática",
  PROB_ESTAT = "Probabilidade e Estatística",
  TECNOLOGIA = "Tecnologia",
  ASTRONOMIA = "Astronomia",
  FISICA = "Física",
  QUIMICA = "Química",
  GEOGRAFIA = "Geografia",
  BIOLOGIA = "Ciências Biológicas",
  ENGENHARIA = "Engenharias",
  MEDICINA = "Medicina",
  AGRO = "Ciências Agrárias",
  DIREITO = "Direito",
  ADM = "Administração",
  ECONOMIA = "Economia",
  ARQ = "Arquitetura",
  HIST = "História",
  POLITICA = "Ciências Políticas",
  LETRAS = "Letras",
  ARTES = "Artes",
  OUTROS = "Outros"
}
